### ISSUE TITLE
Axis selections as list of indices don't work with `mpiarray`

### ISSUE THREAD

**Issue by tristpinsm** [radiocosmology/draco#137]
Although `LoadFilesFromParams` accepts lists of indices for axis selections, it appears that `caput.mpiarray` only supports slices.

Here is the relevant traceback for a pipeline that attempted to use `LoadFilesFromParams` with a `freq_index` property.

```  File "/project/6003614/tristpm/maps/code/draco/draco/core/task.py", line 317, in next 
    output = self.process()
  File "/project/6003614/tristpm/maps/code/draco/draco/core/io.py", line 528, in process
    cont = self._load_file(file_)
  File "/project/6003614/tristpm/maps/code/draco/draco/core/io.py", line 434, in _load_file
    cont = new_cls.from_file(
  File "/project/6003614/tristpm/maps/code/caput/caput/memh5.py", line 1550, in from_file
    data = MemGroup.from_hdf5(
  File "/project/6003614/tristpm/maps/code/caput/caput/memh5.py", line 469, in from_hdf5
    self = _distributed_group_from_hdf5(
  File "/project/6003614/tristpm/maps/code/caput/caput/memh5.py", line 2601, in _distributed_group_from_hdf5
    _copy_from_file(f, group, selections)
  File "/project/6003614/tristpm/maps/code/caput/caput/memh5.py", line 2568, in _copy_from_file
    pdata = mpiarray.MPIArray.from_hdf5(
  File "/project/6003614/tristpm/maps/code/caput/caput/mpiarray.py", line 659, in from_hdf5
    gshape.append(_len_slice(sl, l))
  File "/project/6003614/tristpm/maps/code/caput/caput/mpiarray.py", line 1110, in _len_slice
    start, stop, step = slice_.indices(n)
AttributeError: 'list' object has no attribute 'indices'```

**Comment by tristpinsm** [comment]
@nritsche maybe

**Comment by anjakefala** [comment]
Oh, this is me! 

Can you try with the caput `mpiarray` branch, and let me know if the same error is occurring?

**Comment by tristpinsm** [comment]
> Can you try with the caput `mpiarray` branch, and let me know if the same error is occurring? You can DM me on Slack.

Do you expect it to work? Taking a look at that branch, it's not obvious to me that the `from_hdf5` method has changed in a way that will fix the issue.

**Comment by tristpinsm** [comment]
all you need to make this happen is a pipeline like this

```
pipeline:

    logging:
        root: DEBUG
        h5py: INFO

    tasks:

      - type: draco.core.task.SetMPILogging
        params:
            level_rank0: DEBUG
            level_all: INFO

      - type: draco.core.io.LoadFilesFromParams
        out: sstream
        params:
            files: "/project/rpp-chime/chime/chime_processed/stacks/rev_03/all/sstack.h5"
            selections:
                freq_index: [ 333, 461 ]
```
