### ISSUE TITLE
Allow setting arbitrary attributes via params in tasks

### ISSUE THREAD

**Issue by jrs65** [radiocosmology/draco#154]
This enhancement is to add to `draco.core.task.SingleTask` a config option which allows setting of arbitrary output parameters on any BasicCont style outputs.

This would be something like:
```
<task stuff>
params:
    attributes:
        tracer: QSO
        oldtag: "oldtag_{tag}"
```
where the `{...}` allows interpolation of strings using any item already within the params (plus maybe the `count` parameter from each task).
